### ISSUE TITLE
Problème affichage du nombre de vidéos dans le sous-thème d'une chaîne

### ISSUE THREAD

**Issue by laurinesaj** [EsupPortail/Esup-Pod#1007]
Bonjour, 

L'affichage du nombre de vidéos contenues dans un thème organisé en sous-thèmes indique "0", alors que les sous-thèmes contiennent bien plusieurs vidéos. L'incrémentation n'est prise en compte que si le contenu est rangé en dehors de ces sous-thèmes, dans la racine du thème.

![2023-11-27 16_40_26-Lille Pod - 2023-24 L3-S5 SEF BCC4](https://github.com/EsupPortail/Esup-Pod/assets/149047188/74f0bdf4-3d2f-42b2-8cf2-b5d9292b19e1)
![2023-11-27 16_44_15-Lille Pod - BCC4-S5](https://github.com/EsupPortail/Esup-Pod/assets/149047188/3f1d99d3-9fac-469b-ada0-645cdcfaa2f3)

**Comment by LoicBonavent** [comment]
Bonjour,

Le chiffre affiché proche d'un thème correspond au nombre de vidéos rattachées directement à ce thème, et non l'ensemble des vidéos rattachées aux sous-thèmes.
En fait, même s'il y a une notion de hiérarchie parent / fils, chaque thème est indépendant.

Par contre, il est possible de rattacher une vidéo à un thème et à un de ces sous-thèmes, dans le même temps.
Dans ce cas là, la vidéo sera comptabilisée et dans le thème et dans le sous-thème.

Bonne journée

**Comment by LoicBonavent** [comment]
Bonjour,

Si cela vous convient, je me permets de clôturer ce ticket.

Bonne journée

**Comment by laurinesaj** [comment]
Bonjour Loïc,
Merci pour les explications.
Cela rend l'information compliquée à lire pour les chaînes ayant une structure et du contenu assez conséquents, car soit on fait l'impasse sur l'affichage dans les thèmes du nombre "réel" de vidéos, soit on fait apparaître la vidéo à plusieurs niveaux de hiérarchie, ce qui rend le sous thème "inutile".
Le ticket peut être clos.
