### ISSUE TITLE
Plus possible de téléverser un fichier VTT ?

### ISSUE THREAD

**Issue by Badatos** [EsupPortail/Esup-Pod#1012]
Il ne semble plus possible de téléverser un fichier VTT dans l'éditeur de sous-titres.
Avant, on pouvait le faire en cliquant sur "Sélectionner un fichier". Mais à présent, c’est vide :
![image002](https://github.com/EsupPortail/Esup-Pod/assets/12731381/4d88c334-89d7-4ae7-8b0f-f09805f16cff)

 
Test effectué sous Chrome par Anna Vetter le 27/11/2023.

**Comment by Badatos** [comment]
Testé ce jour sur Esup-Pod 3.4.1 et le bug ne se produit pas.
Hypothèse : Bug lié à #1010 ?

**Comment by Badatos** [comment]
Je confirme l'hypothèse ci-dessus : Quand webpush est activé, le bug ne se produit pas. la PR #1011 va corriger cela.

**Comment by DeprezLaurent** [comment]
Bonjour, nous avons désactivé webpush et rencontrons l'erreur ci-dessous sur le bouton "remplacer" un fichier vtt ou "sélectionner":
Uncaught ReferenceError: gettext is not defined
<anonymous> https://podeduc.apps.education.fr/static/podfile/js/filewidget.js:9

Uncaught (in promise) TypeError: document.csrfmiddlewaretoken is undefined
    sendandgetform https://podeduc.apps.education.fr/static/js/completion.js?ver=3.4.1:205
    <anonymous> https://podeduc.apps.education.fr/static/js/completion.js?ver=3.4.1:126
    EventListener.handleEvent* https://podeduc.apps.education.fr/static/js/completion.js?ver=3.4.1:96
