### ISSUE TITLE
Bug Transcription depuis la page d'édition d'une vidéo

### ISSUE THREAD

**Issue by MathieuDomingo** [EsupPortail/Esup-Pod#1017]
Salut, on me remonte un petit bug pour la transcription.

Étapes pour reproduire le problème : 
 - Editer une vidéo qui n'a rien de sélectionné dans le Champs "Transcrire" (ligne avec des tirets)
 - Choisir une langue dans le champs "Transcrire" (Français par exemple) 
 - Cliquer sur le bouton "Relancer la Transcription"

Résultat attendu : Avoir une transcription en français
Résultat obtenu : L'admin reçois un mail :
Error Encoding Video id : 150
no stt model found for lang:.Please add it in TRANSCRIPTION_MODEL_PARAM.
Suite à ça l'utilisateur n'a plus le bouton "Relancer la Transcription" si il va de nouveau éditer la vidéo (et le champs Transcrire est de nouveau sur les tirets) 
Conclusion : Cela ne sauvegarde pas le fait que l'on vient de choisir une langue avant de lancer la transcription

Idée de solution potentiel : il faudrait que le bouton "Relancer la Transcription" sauvegarde le formulaire avant de lancer la transcription 

Idée de contournement du problème : il faudrait que le bouton "Relancer la Transcription" ne soit pas présent si il n'y a que des tirets dans le champs "Transcrire" pour obliger à sauvegarder la page puis ensuite à cliquer sur "Relancer la Transcription".
(Remarque : je suppose que cela doit aussi bug si l'on passe d'une langue à une autre langue et ce contournement ne fonctionnera pas dans ce cas la, cela relancera juste la Transcription dans la langue de départ)

A minima : Afficher le bouton "relancer la Transcription" aussi sur erreur de la forme "-1 : no stt model found for lang:" pour que l'utilisateur puisse peut être tomber sur la bonne séquence d'actions à faire (modifier la langue, sauvegarder , cliquer sur le bouton relancer la Transcription)

**Comment by ptitloup** [comment]
En fait, le problème vient du fait que la transcription est lancée sans l'information de la langue de transcription selectionnée puisque non enregistrée dans la vidéo. Je regarde pour fixer ce point.

**Comment by ptitloup** [comment]
Ok pour moi, je viens de proposer un ensemble de modifications dans ma PR. Je vous laisse voir si cela vous convient
