### ISSUE TITLE
Fix timestamp inputs in cut page.

### ISSUE THREAD

**Issue by AymericJak** [EsupPortail/Esup-Pod#1070]
![image](https://github.com/EsupPortail/Esup-Pod/assets/106442526/3e551818-5c74-400e-90c2-c8aa82a769de)

We should only see the video time.

--> Fix time format

**Comment by SebastienCozeDev** [comment]
Après vérification, le bug n'est plus présent. Le format du temps est de nouveau correct.

![image](https://github.com/EsupPortail/Esup-Pod/assets/96086580/a377c0f0-a9f7-4522-bfa1-ffe95cad5f74)

**Comment by AymericJak** [comment]
Mon ordinateur est en version anglaise.
Ce problème est peut être dû d'où le `AM`

**Comment by SebastienCozeDev** [comment]
Effectivement, le bug est présent lorsque le navigateur est en anglais
