### ISSUE TITLE
Bulk update : `" " n'est pas une valeur correcte.`

### ISSUE THREAD

**Issue by Badatos** [EsupPortail/Esup-Pod#1081]
Lorsqu'on veut ajouter un mot de passe à plusieurs vidéos en même temps, quand on applique les modifs y a un message d'erreur comme quoi il faut choisir un "groupe" mais il y en a pas.
Message d'erreur `" " n'est pas une valeur correcte.`.
Par contre, en passant par la page d'édition d'une vidéo, le champs "groupe" n'est pas obligatoire pour enregistrer les modifications.

**Comment by ptitloup** [comment]
Je vais regarder et fixer dans la PR #1078 avec Sebastien et Aymeric. Nous sommes preneur de tout retour.

**Comment by AymericJak** [comment]
Problème corrigé dans la PR #1078
