### ISSUE TITLE
Découpage de vidéo pour les propriétaires additionnels

### ISSUE THREAD

**Issue by cbissler** [EsupPortail/Esup-Pod#1083]
Actuellement un propriétaire additionnel ne peut pas découper une vidéo, le bouton n'est pas disponible. Est-ce volontaire ?

**Comment by Badatos** [comment]
A priori, c'est bien un bug, bien vu ^^
Sur notre instance (3.5.0) j'ai cette erreur Javascript :
`Uncaught SyntaxError: missing ) after argument list`
Lors de l'appel à linkTo_UnCryptMailto('b'XXXXXXX=='');

**Comment by fanfounet** [comment]
#1097

**Comment by fanfounet** [comment]
Disponible dans la version 3.6
