### ISSUE TITLE
Action en masse sur les chaines

### ISSUE THREAD

**Issue by cbissler** [EsupPortail/Esup-Pod#1106]
Bonjour,
Depuis le dasboard si on souhaite modifier en masse la chaine de plusieurs vidéos le formulaire propose 2 champs : Les chaines et les thèmes. 
La liste déroulante des chaines est vide et la liste des thèmes contient tous les thèmes, toutes chaines confondues.
Du coup il est impossible de sélectionner un chaine sans thème et cela ne fonctionne pas.
Est-ce que vous constatez ce problème (je suis en 3.5.2)?

**Comment by Badatos** [comment]
Chez moi, le champ Chaine contient bien la liste des chaines (en dynamique), mais en effet si je selectione une chaine sans mettre de theme, j'ai l'erreur "«  » n’est pas une valeur correcte."

**Comment by FBrosset** [comment]
J'ai le même comportement que toi @Badatos . J'ai fais F12 avant d'afficher les chaines et Pod fait appel à Redis pour les récupérer.

**Comment by cbissler** [comment]
On peut sélectionner une chaine et un thème d'une autre chaine le formulaire est valide par contre la vidéo se voit affecter à la chaine et au premier thème de cette dernière. Le thème de l'autre chaine n'est pas enregistré
