### ISSUE TITLE
Suppression en masse depuis le tableau de bord

### ISSUE THREAD

**Issue by cbissler** [EsupPortail/Esup-Pod#1111]
Bonjour,

Nous avons constaté 2-3 bricoles sur la suppression en masse de vidéo.

Déjà avant de parler de la suppression, quand on choisit une action on ne peux plus la dé-sélectionner on ne peut qu'en choisir une autre, si on a sélectionné des options à l'action elles restent. Est-ce que le bouton "Effacer la sélection" ne pourrait pas s'appeler "Réinitialiser" et désélectionner également les actions et leurs options ?

Ensuite le message de demande de confirmation parle "d'édition" et non pas de "suppression".
![Capture d’écran 2024-04-18 à 16 01 36](https://github.com/EsupPortail/Esup-Pod/assets/2891363/541129ec-0d36-4522-8f85-412e780536e0)

Une fois qu'on a supprimé les n vidéos restent sélectionnées dans le formulaire alors qu'elles n'existent plus. Pour le cas de la suppression le formulaire devrait être réinitialisé.
![Capture d’écran 2024-04-18 à 16 02 08](https://github.com/EsupPortail/Esup-Pod/assets/2891363/c8322c1f-0f63-473c-a863-f97c95b2b5da)

Enfin, au point où j'en suis, on m'a remonté comme perturbant que le fait que de cliquer sur une vidéo depuis le dashboard ne l'ouvrait plus comme avant mais la sélectionnait et qu'il fallait désormais cliquer sur un bouton spécifique pour l'ouvrir. On fait plus souvent l'inverse, ouvrir des videos que de la modif en masse. Que pensez-vous de faire en sorte qu'un clique sur la vignette ouvre la vidéo et qu'une box à cocher en haut à droite par exemple permette la sélection ? Ce qui en plus ôterait un bouton de la bande qui contient déjà éditer, compléter, chapitrer, cut, habiller, supprimer...

Merci d'avoir lu jusqu'au bout :-)

**Comment by AymericJak** [comment]
L'ensemble des remarques ont été prises en compte.

Les corrections des premières remarques ont été appliquées en version 3.6.0.

La dernière remarque sera quant à elle corrigée dans une version mineure de la 3.6.x :

> Enfin, au point où j'en suis, on m'a remonté comme perturbant que le fait que de cliquer sur une vidéo depuis le dashboard ne l'ouvrait plus comme avant mais la sélectionnait et qu'il fallait désormais cliquer sur un bouton spécifique pour l'ouvrir. On fait plus souvent l'inverse, ouvrir des videos que de la modif en masse. Que pensez-vous de faire en sorte qu'un clique sur la vignette ouvre la vidéo et qu'une box à cocher en haut à droite par exemple permette la sélection ? Ce qui en plus ôterait un bouton de la bande qui contient déjà éditer, compléter, chapitrer, cut, habiller, supprimer...
