### ISSUE TITLE
Entête des vignettes liste de lecture

### ISSUE THREAD

**Issue by cbissler** [EsupPortail/Esup-Pod#1118]
Bonjour,
Les entêtes de vignettes de playlists contiennent une icône "horloge" qui n'a pas vraiment lieu d'être (sans doute un reste de copier/coller d'une vignette de vidéo dont on affiche la durée) car elle précède le titre de la playlist. Pourrait-on la retirer ou mettre autre chose ?
De plus l'affichage du nombre de vidéo (collé en dessous et décalé) n'est pas très heureux mais ça c'est peut-être dû à notre thème. Il faudrait vérifier.
![image](https://github.com/EsupPortail/Esup-Pod/assets/2891363/2bc84d28-63be-4ae9-a826-2075bde41e0a)

**Comment by AymericJak** [comment]
Je l'avais déjà corrigé dans la PR #1117 !! :grin:
