### ISSUE TITLE
Les vidéos privées sont listées publiquement sur la page `/videos/`

### ISSUE THREAD

**Issue by cloudy-oasis** [EsupPortail/Esup-Pod#1128]
Bonjour,

Lorsqu'on visite `/videos/`, les vidéos restreintes et/ou protégées par mot de passe apparaissent dans les résultats, peu importe si on y a accès. Cela ne permet pas de voir la vidéo elle-même, mais il est quand même possible de voir des métadonnées sensibles. On s'attendrait à ce que seules les vidéos publiques ou nous étant accessibles soient listées :

|                  | Publique | Restreinte | Avec mot de passe |
| ---------------: | :------- | :--------- | :---------------- |
|     Propriétaire | Oui      | Oui        | Oui               |
|  Co-propriétaire | Oui      | Oui        | Oui               |
| Membre de groupe | Oui      | Oui        | Non               |
|       Connecté⋅e | Oui      | [^1]       | Non               |
|          Anonyme | Oui      | Non        | Non               |

[^1]: Si restreinte sans groupes

J'observe ce bug sur Pod 3.6.1 (commit be947445) et Firefox 115 (mais Firefox ne devrait pas être lié au problème).

J'ai écrit un fix que je peux proposer en PR.

Merci d'avance pour votre réponse !

**Comment by ptitloup** [comment]
Bonjour,
Il est tout à fait normal de lister les vidéos en accès restreint (mot de passe ou authentification) dans la page des vidéos. Seules les vidéos "brouillon" ne le sont pas. Ce n'est donc pas un bug mais une fonctionnalité.
N'hésitez pas si vous souhaitez plus d'information
Cordialement

**Comment by ptitloup** [comment]
N'hésitez pas à me dire si vous travaillez ou représentez un établissement et si cette fonctionnalité doit être proposée

**Comment by cloudy-oasis** [comment]
Je travaille avec @ASponch dans le cadre de mon stage pour l'UPJV.

Je ne suis pas sûre de comprendre le but de la fonctionnalité. Considérant que les vidéos ont été mises en ligne privées et qu'elles ne sont pas accessibles par les visiteurs lambda, ne devraient-elles pas être masquées de la liste des vidéos ? Cela me paraît faire fuiter des informations privées des publicateurs et offrir une moins bonne UX aux visiteurs. Y a-t-il une raison que je ne saisis pas ?

**Comment by Badatos** [comment]
En réalité le terme "privé" n'est pas utilisé pour les vidéo de Pod. Elles ne sont donc pas mise en ligne en mode "privé", mais avec un "accès restreint" (par mot de passe ou authentification)

**Comment by cloudy-oasis** [comment]
En effet, je n'avais pas bien compris le fonctionnement du mode brouillon :sweat_smile:

Dans ce cas, pourrait-il être intéressant de rajouter une fonctionnalité empêchant la vidéo d'être listée publiquement, sans pour autant en restreindre l'accès ? Actuellement, il n'est pas possible de partager une vidéo à quelqu'un sans rendre cette personne (co-)propriétaire de la vidéo (ce qui n'est pas toujours possible, notamment si elle ne possède pas de compte). Dans notre cas précis, l'UPJV partage souvent des vidéos à des organisateurs d'évènements sans les lister avant de les publier. Ces personnes n'ayant généralement pas de compte, le mode brouillon ne leur permettrait pas de les visionner. Une telle fonctionnalité permettrait de leur partager la vidéo sans la rendre visible.

Comme plus tôt, je peux écrire et PR une telle fonctionnalité si c'est le cas :slightly_smiling_face:

**Comment by ptitloup** [comment]
Si il existe des partages de vidéo en mode "brouillon". La vidéo n'est pas listé, elle n'est accessible que par ceux ayant un lien avec un token d'accès.

**Comment by ptitloup** [comment]
en 3.6.1, laisse ta video en mode brouilloin et sur la page d'edition ou de visualisation, tu as un lien vers la génération de token. cela ta permet de générer des token et des liens d'accès à ta vidéo

**Comment by ASponch** [comment]
Bonsoir ptitloup, Badatos et cloudy-oasis,

Merci à tous pour vos retours. Je n'ai pas d'instance de test sous la main mais je conçois qu'il est possible de partager une vidéo en mode "Brouillon", c'est assez logique en fait (cela serait a ajouter dans la documentation utilisateur).

Maintenant, et je vais me faire l'avocat du diable mais lorsque l'on va sur unicapod (au hasard ;) ) dans la partie "toutes les vidéos" (https://pod.univ-cotedazur.fr/videos/), je rejoinds notre stagiaire sur le fait que quasi aucune vidéos n'est en accès libre.

En terme d'UX, cela n'est pas très intérressant et il semble normal que les vidéos ne soient pas listées pour l'utilisateur non connecté et, à contrario, une fois connecté qu'elles apparaissent.

Cela permettrai d'éviter de divulguer des métadonnées permettant d'accéder à des vidéos protégées (je n'ai pas de lien sous la main mais c'est très facile à obtenir ; il faut récupéré le hash, remplacer /media/files par /media/videos et remplacer le nom de la vidéo par "720p.mp4" avec l'ID du repertoire). Je l'ai fait en "live" devant notre stagiaire mais je dois être fatigué ce soir, je n'y arrive plus !

Enfin, je vois un dernier cas d'usage, assez rare mais existant, où l'orateur tape son nom dans Google (Bing, etc...) et me dis, "lorsque je tape mon nom, on tombe sur une page d'une vidéo et je ne souhaites pas être recensé, merci d'effacer cela".

Bien à vous,
--
Adrien

**Comment by ptitloup** [comment]
Bonjour,
Je comprends votre point de vue. On a un comité technique cet après midi ou l'on pourra echanger de cela. Toutefois, les orateurs et autres informations concernant la video en accès restreint ne sont pas "connues" seul le depositaire, le titre et la vignette sont accessibles.
Nicolas

**Comment by cloudy-oasis** [comment]
Rebonjour,

Merci @ptitloup ! J'ai regardé et la fonctionnalité de tokens d'accès est effectivement présente, je ne l'avais pas trouvée

Je peux confirmer ce que voit @ASponch mais je pense que c'est dû au fait que la documentation (utilisateur ou technique) ne mentionne pas cette fonctionnalité. Mais bon, même si elle était décrite en détail, ce serait probablement toujours le cas :smile:

Puisque la fonctionnalité existe effectivement, je pense que cette issue est réglée, je vous laisse la fermer quand vous voulez :slightly_smiling_face:
