### ISSUE TITLE
La vignette uploadée pendant l'ajout d'une vidéo n'est pas positionnée sur la vidéo après encodage

### ISSUE THREAD

**Issue by FredNass** [EsupPortail/Esup-Pod#1150]
Bonjour,

Je vous soumets ce qui me semble être un bug (version utilisée 3.4.1).

Procédure : 

1/ L'utilisateur dépose une vidéo.
2/ Il renseigne les champs du formulaire et upload une vignette personnalisée pour cette vidéo.
3/ Il enregistre le formulaire.
4/ L'encodage de la vidéo se termine.
5/ L'utilisateur ouvre la page de sa vidéo

Comportement observé : 

La vignette qui apparait sur la vidéo n'est pas celle que l'utilisateur a déposée au moment de l'ajout de la vidéo.
A la place, c'est une vignette extraite de la vidéo qui apparait.

Comportement attendu : 

La vignette déposée par l'utilisateur devrait apparaitre sur la vidéo.

Si la solution permet de définir une vignette au moment du dépôt, celle-ci devrait être utiliséé dès la vidéo encodée.
L'utilisateur ne devrait pas avoir à rééditer sa vidéo pour modifier la vignette.

**Comment by ptitloup** [comment]
Bonjour, nous avons préféré retirer la possibilité de choisir une vignette avant et pendant l'encodage car l'encodage génére et affecte une vignette à la vidéo. Il est tjs possible de la changer par la suite. Merci pour votre retour qui nous permet d'améliorer l'expérience utilisateur de la palteforme
