### ISSUE TITLE
Un propriétaire additionnel ne peut pas modifier les sous-titres déjà présents

### ISSUE THREAD

**Issue by Syl20D20** [EsupPortail/Esup-Pod#1166]
Bonjour,

J'ai découvert qu'un propriétaire additionnel n'a pas la possibilité la possibilité de modifier les sous-titres déjà présents sur une vidéo et se retrouve avec un message d'erreur : 
![image](https://github.com/EsupPortail/Esup-Pod/assets/98822350/3d1020bd-a896-4881-aad0-9059247e7347)

Merci.

**Comment by Badatos** [comment]
Bonjour,
Quelle est la version d’Esup-Pod sur laquelle vous constatez ce souci ?

**Comment by Syl20D20** [comment]
Bonjour,

Nous sommes en version 3.6.

**Comment by Badatos** [comment]
Merci :)

Je confirme le bug : lorsqu'un propriétaire additionel tente de modifier un sous-titre existant, l'erreur suivante apparait :
```
Erreur durant le téléversement(SyntaxError: JSON.parse: unexpected character at line 5 column 1 of the JSON data)
Aucune donnée ne peut être stockée.
```

**Comment by Badatos** [comment]
Suite des investigations : l'objet envoyé à JSON.parse est en fait une page HTML de pod affichant l'erreur suivante :
```
Accès refusé

Vous n’avez pas accès à cette page.
```

Ce qui confirme bien l'erreur de droit d'acces

**Comment by Badatos** [comment]
La prochaine version de Pod devrait empêcher le souci de se reproduire.
Pour mettre à jour les droits sur une vidéo, il suffira d'enregistrer sa page de parametres.

Et pour un nettoyage complet, je recommande de lancer au moins une fois
```sh
python manage.py clean_video_files --type=userfolder
```
(avec l'option `--dry` si vous voulez juste voir ce que ca fait avant de nettoyer réellement)

nb : avec `--type=all` ça fonctionne aussi, si vous voulez au passage nettoyer des fichiers video non associés à un objet video
