### ISSUE TITLE
La transcription automatique produit des sous-titres trop longs

### ISSUE THREAD

**Issue by l-leroux** [EsupPortail/Esup-Pod#1204]
Bonjour,
cela fait plusieurs fois que je remarque que la  transcription automatique produit des sous-titres trop longs, bien au-delà des 80 caractères qui sont acceptés par l'outil d'édition des sous-titres.
Cela rend la modification, même à la marge des sous-titres beaucoup plus pesante que nécessaire, étant donné qu'il faut découper tous les sous-titres dépassant 80 caractères pour que l'outil d'édition accepte la saisie d'une modification.
Exemple : https://podeduc.apps.education.fr/video/59115-presentation-des-exercices-mathalea-utilisant-instrumenpoche-pour-la-correction/
Merci !

**Comment by l-leroux** [comment]
(en fait, j'ai dû supprimer le fichier de sous-titre car la vidéo allait être publiée dans une newsletter)

**Comment by DeprezLaurent** [comment]
Bonjour, 
Le problème sera résolu avec la prochaine montée de version de PodEduc. 
Dans l'attente vous pouvez télécharger le fichier vtt, faire les corrections et le téléverser et associer à la vidéo.
