### ISSUE TITLE
Bug d'intégration iframe sur Moodle

### ISSUE THREAD

**Issue by Syl20D20** [EsupPortail/Esup-Pod#1207]
Bonjour,

Depuis quelques temps, l'intégration d'une vidéo Pod (3.8.1) sur Moodle (4.1.13+), dans une zone texte media par exemple, génère un ascenseur alors que cela ne le faisait auparavant. C'est assez embêtant car cela alourdi l'interface et masque la barre d'outils de contrôle de lecture.

**Comment by LoicBonavent** [comment]
Bonjour,
En testant dans mon environnement, je n'arrive pas à reproduire ce problème d'ascenseur, mais cela pourrait avoir de nombreuses causes.
Par hasard, y aurait-il moyen d'accéder à un tel cours pour tester ?
Bonne journée

**Comment by Syl20D20** [comment]
Bonjour,

En revérifiant, je m'aperçois que le problème a disparu donc affaire réglé.

Cordialement.
