### ISSUE TITLE
[BUG] problème de protection des vidéos restreintes dans les playlists (Pod 3.4.1 et 3.8.1)

### ISSUE THREAD

**Issue by sabinanina** [EsupPortail/Esup-Pod#1222]
Pour info **ce bug sera corrigé en 3.8.2 via la PR #1217**. Information confirmée par Loïc Bonavent :) 

Lorsqu'une vidéo est définie en mode restreint (Pod 3.4.1) ou restreinte par authentification (Pod 3.8.1) et incluse dans une playlist publique, la protection de la vidéo est annulée. 
En accédant à la vidéo via la playlist, la restriction d'accès n'est plus effective, ce qui permet à des utilisateurs non authentifiés de la visionner.
La protection d'une vidéo restreinte ne devrait pas être levée dans une playlist publique.

Pour reproduire le bug :
1. Ajouter une vidéo restreinte (par restriction ou par authentification) dans une playlist publique.
2. Se déconnecter de Pod. Vider le cache et/ou accéder à Pod (sans s'authentifier) dans une fenêtre privée.
3. Essayer d'accéder à la vidéo via la playlist et observer que la vidéo est accessible sans restriction.

**Comment by LoicBonavent** [comment]
Merci pour les tests et l'issue.
