### ISSUE TITLE
Utilisation de PostGreSQL

### ISSUE THREAD

**Issue by CJosso** [EsupPortail/Esup-Pod#241]
Bonjour,

A priori l'application utilise Django sans discuter avec la base de données directement.
Y a-t-il une limitation d'utilisation pour PostGreSQL, sachant que Django prend officiellement en charge PostGre ?
Ce n'est pas explicitement interdit, mais ça n'est pas évoqué non plus dans les docs d'installation.

Merci d'avance,
Clément

**Comment by ptitloup** [comment]
Bonjour,
En effet, vous pouvez brancher votre instance de Pod sur une basse de donnée PostGreSQL.
Vous trouverez à cette adresse la documentation permettant de le faire : https://docs.djangoproject.com/fr/1.11/ref/databases/#postgresql-notes
Il me semble que plusieurs établissement de l'ESR ont fait ce choix, je vous invite à envoyer un mai sur la liste de diffusion pour tout renseignement complémentaire.
Bonne journée
