### ISSUE TITLE
ElasticSearch complain in default settings

### ISSUE THREAD

**Issue by CJosso** [EsupPortail/Esup-Pod#276]
Bonjour,

On a default install, elasticsearch won't work.
It complains about text search :
```
RequestError at /search/

RequestError(400, 'search_phase_execution_exception', 'Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [cursus] in order to load field data by uninverting the inverted index. Note that this can use significant memory.')
```
It is explain here : https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html

Elasticsearch is in version 7.7, but 6.8 seems to do the same.
Clément.

**Comment by ptitloup** [comment]
Bonjour Clément, 
as-tu installé le plugin ICU https://www.elastic.co/guide/en/elasticsearch/plugins/master/analysis-icu.html puis redémarrer elasticsearch pour voir ? Pour une meilleur réactivité, tu peux utiliser la liste pod. 
Nicolas

**Comment by CJosso** [comment]
Oui le plugin est installé.
Cela semble plutôt être une incompatibilité lié aux nouvelles version d'elasticsearch.
D'ailleurs la version 7.7 ne supporte pas create_pod_index a cause d'une directive plus supportée : 
```
(py-pod-venv) [toutapod@praca-pod-front-1-lva video_search]$ curl -X PUT -H "Content-Type: application/json" -d @search_template.json 192.168.86.221:9200/pod
{"error":{"root_cause":[{"type":"parse_exception","reason":"unknown key [template] for create index"}],"type":"parse_exception","reason":"unknown key [template] for create index"},"status":400}
```
Sachant que le script considère qu'une erreur 400 est bonne, cela fail sans message informatif en passant par manage.py

Il faudrait peut-être mettre une version elasticsearch maximum.

**Comment by ptitloup** [comment]
Oui version 6.8, ca fonctionne sur deb10. Merci pour la remarque. Puis-je savoir pour quelle instance faites-vous cette installation ?

**Comment by CJosso** [comment]
C'est une future instance v2 pour l'académie de Rennes sur RHEL8.
Sinon je n'ai pas trouvé de mailing list pod, c'est où ?

**Comment by ptitloup** [comment]
voici l'adresse de la mailing list : pod@esup-portail.org
N'hésitez pas à envoyer un mail et je pourrais vous y abonner. Vous pourrez me confirmer que ca fonctionne bien avec ES6.8 ? Bonne continuation
