### ISSUE TITLE
If SSL is handled by a proxy, embed codes and share links are HTTP

### ISSUE THREAD

**Issue by Deelight-fr** [EsupPortail/Esup-Pod#313]
When using Pod behind an SSL proxy (clients connect to the proxy using HTTPS, proxy connects to Pod frontal using HTTP), embed codes and video sharing links contain HTTP (not S) urls. Maybe a setting in the config file could be added to force the generation of HTTPS links (for example, `SSL_PROXY = True`)?

**Comment by ptitloup** [comment]
Is-ti ok ? You can add some configuration to force https. You can add this 3 lines in your settings_local.py :
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True 
Regards

**Comment by Deelight-fr** [comment]
Thanks, it works fine with `SECURE_SSL_REDIRECT = True`.
I just had to add a `X-Forwarded-Proto: https` header on my SSL proxy to avoid an infinite redirect.
