### ISSUE TITLE
Reference to a video extract (with an `end` parameter)  

### ISSUE THREAD

**Issue by benel** [EsupPortail/Esup-Pod#336]
Bonjour et merci pour ce joli projet.

Pour rendre un cours plus interactif, il est courant d'intercaler la vidéo avec des "activités" (par exemple des QCM sur Moodle). Dès lors, il y a deux possibilités : 
- soit faire une multitude de très courtes vidéos, 
- soit faire une seule vidéo et référencer des extraits avec un **début** et une **fin**.

Sur YouTube, par exemple, ce sont les paramètres `start` et `end`.
Sur Pod, j'ai trouvé `start` mais y a-t-il l'équivalent de `end` ?

L'idée serait de pouvoir intégrer ce genre d'URI : `https://pod.acme.edu/video/super-cours/?start=191&end=249`.

Merci d'avance.

**Comment by ptitloup** [comment]
Bonjour,
En effet, il serait intéressant de pouvoir rajouter un end time. Cette possibilité n'est pour l'instant pas implémenté sur Pod mais je vous invite à en faire part sur la liste de diffusion et si vous pouvez, de faire une proposition d'implémentation.
Bonne soirée
