### ISSUE TITLE
[POD 2.7.1] CSS Bug on User's Podfile

### ISSUE THREAD

**Issue by nothing-fr** [EsupPortail/Esup-Pod#372]
I think there is a problem on the Podfile part of the users, the css is not applied correctly:

![screencapture-videos-test-insa-rennes-fr-podfile-2020-11-04-10_57_07](https://user-images.githubusercontent.com/3938579/98097727-b3c22800-1e8d-11eb-8bcd-c84fd3ee64d6.png)

On the other hand, when a modal window is loaded, it seems to work (and even fixes the user podfile when loaded):

![screencapture-videos-test-insa-rennes-fr-podfile-2020-11-04-10_58_03](https://user-images.githubusercontent.com/3938579/98097735-b58beb80-1e8d-11eb-8b32-1186534d0866.png)

Do you have any clue on how to fix that ?

**Comment by meschac38700** [comment]
Hello @nothing-fr, please run the following command to reload your static files and finally restart your server:
python manage.py collectstatic --noinput --clear

**Comment by nothing-fr** [comment]
it's the same, except that it erased my interface customizations ... ( no more custom files in: django_projects/podv2/pod/static/custom/css)

I still have the same display bug but with default theme.

```
Deleting 'modeltranslation/css/tabbed_translation_fields.css'
Deleting 'modeltranslation/js/clearable_inputs.js'
Deleting 'modeltranslation/js/force_jquery.js'
[...]
Copying '/home/pod/.virtualenvs/django_pod/lib/python3.6/site-packages/h5pp/static/h5p/styles/bootstrap/js/bootstrap.js'
Copying '/home/pod/.virtualenvs/django_pod/lib/python3.6/site-packages/h5pp/static/h5p/styles/bootstrap/js/bootstrap.min.js'
Copying '/home/pod/.virtualenvs/django_pod/lib/python3.6/site-packages/h5pp/static/h5p/styles/bootstrap/js/npm.js'

2066 static files copied to '/usr/local/django_projects/podv2/pod/static'.
```
![screencapture-videos-test-insa-rennes-fr-podfile-2020-11-04-14_03_22](https://user-images.githubusercontent.com/3938579/98115102-8fbf1080-1ea6-11eb-87b0-7de2b7224eb2.png)

**Comment by nothing-fr** [comment]
Ok, i've just found why ! A change in `base.html` template !

I use a custom one !
