### ISSUE TITLE
Vitesse accélérée

### ISSUE THREAD

**Issue by Koopa-13** [EsupPortail/Esup-Pod#380]
Bonjour, après de nombreux essais, je n'arrive pas à trouver le bouton pour sélectionner la vitesse (*0,5, *1, *1,5 ou *2). 
Je l'ai vu affichée à un moment, mais ce n'est arrivé qu'une fois, même en essayant depuis un autre appareil ou navigateur. 
Savez-vous comment l'afficher à nouveau ?

En te remerciant par avance,
Victor

**Comment by JoshuaBaubry** [comment]
Bonjour ! Nous sommes au courant de ce bug et il sera réglé dans une future version. De ce que j'en ai compris la fonctionnalité de vitesse accélérée ne fonctionnait pas sous chrome.

**Comment by Koopa-13** [comment]
Merci beaucoup !
