### ISSUE TITLE
Envoi de vidéo sur site en anglais

### ISSUE THREAD

**Issue by Badatos** [EsupPortail/Esup-Pod#386]
Bonjour,
J'ai un bug qui se produit lorsque je tente d'envoyer une nouvelle vidéo alors que le site est en anglais. (Je précise que quand Pod est en francais, ca se passe bien)

J'envoie une vidéo en mode "chunk", elle s'upload correctement, et quand l'upload est terminé, La redirection vers la page d'édition ne se fait pas correctement, j'obtiens une page 404 :

```
/video_edit/0024-cr4ctere-videomp4/ Not found
No Video matches the given query.
```

==> et en effet, pour obtenir la vidéo il faut aller à cette adresse : 
/video_edit/0024-/

==> Apparemment quand le site est en anglais, l'upload ne met pas à jour son titre.

D'ailleurs, le mail reçu après l'encodage confirme qu'il n'y a pas de titre :
`Le contenu "" a été encodé au format web, et est maintenant disponible sur UCAPod.
Vous la retrouverez ici:
[...]/video/0024-/
`

**Comment by JoshuaBaubry** [comment]
Pod est en quelle version ?

**Comment by JoshuaBaubry** [comment]
Je mon coté j'ai testé dans la dernière version et tout marche bien

**Comment by Badatos** [comment]
> Pod est en quelle version ?

Ca se produit sur mon serveur en 2.7.1

**Comment by JoshuaBaubry** [comment]
Ce bug est normalement corrigé sur la branche de développement, à tester de ton coté

**Comment by ptitloup** [comment]
Ca va sortir avec la 2.7.2
