### ISSUE TITLE
Impossible d'ajouter une vidéo enrichie à une liste de lecture

### ISSUE THREAD

**Issue by Badatos** [EsupPortail/Esup-Pod#401]
Bonjour,
Sur la v2.7.1, lorsqu'on tente d'ajouter la version enrichie d'une vidéo à sa liste de lecture, on a une erreur du serveur.
Avec la même vidéo, en version "originale", ca fonctionne bien par contre.

**Comment by ptitloup** [comment]
Bonjour, 
Votre demande a été prise en compte et est maintenant intégrée dans la dernière version de la plateforme
Bien cordialement

**Comment by Badatos** [comment]
Merci ;)
