### ISSUE TITLE
[BUG] Chunked Uploads et droits utilisateurs

### ISSUE THREAD

**Issue by nothing-fr** [EsupPortail/Esup-Pod#403]
Bonjour,

J'ai remarqué plusieurs choses avec le Chunked Uploads activé :
- Le formulaire pour les infos sur la vidéo n'est affiché qu’après l'upload (je suppose que c'est lié au mécanisme en lui même)
- Un utilisateur qui ne fait pas partie du "Staff" et donc techniquement qui ne doit pas pouvoir upload une vidéo en est capable lorsque l'option est activée. (même si par la suite, il n'a plus le droit d’y accéder, la vidéo est quand même envoyée et encodée)

Cordialement,

**Comment by ptitloup** [comment]
Bonjour,
L'affichage du formulaire après l'upload est voulu. Ce comportement nous permet de gérer l'upload de la vidéo directement.
Pour l'accès, ce bug est corrigé en version 2.7.2 : https://github.com/EsupPortail/Esup-Pod/releases/tag/2.7.2
Merci de vérifier et n'hésitez pas à revenir vers nous 
Bien cordialement
Nicolas CAN

**Comment by nothing-fr** [comment]
On me confirme que le bug est résolu par la 2.7.2 dans l'oreillette, je ferme donc mon ticket !
