### ISSUE TITLE
[REQUEST] Filtrage des vidéos par Cursus

### ISSUE THREAD

**Issue by nothing-fr** [EsupPortail/Esup-Pod#404]
Vu que l'INSA est une école d'ingé, la notion de cursus personnalisable / searchable est très intéressante pour nous, serait-il possible de faire évoluer cette partie ?

Des suggestions :
 - Évolution du "code" nomenclature sur plus de caractères que 1 seul (pas forcement nécessaire mais c'est plus souple)
 - gestion de l'ajout / edit / delete des cursus via l'admin django (plus simple que dans le fichier de conf, surtout pour les fonctionnels sur l'appli)
 - Filtrage des vidéos par cursus (pour les étudiants / profs)

Cela nous permettrais d'avoir une meilleure structuration des vidéos : 

- Cursus (1ère année master truc muche, etc...)
  - Type (enregistrement zoom, conférence, etc...)
    - Discipline (maths, physique, etc...)
      - Tags (tags "extra" pour plus de finesse si besoin)

plutôt que simplement : 

  - Type
    - Discipline
      - Tags

Qui reste trop dépendant du bon renseignement des tags par l'utilisateur (qui n'en a pas forcement l'habitude et les utilisateurs n'ont pas forcement la meme logique la dessus)

Cela permettrais aux élèves / profs de mieux ce retrouver dans les vidéos et de filtrer simplement celles-ci pour leur cursus actuel.

Merci d'avance !
Cordialement.

**Comment by ptitloup** [comment]
Bonjour,
Vous pouvez nous rejoindre sur le chat d'Esup pour echanger sur le projet. Nous serions plus à même de vous aider. Quel est votre établissement de rattachement ?
Bien cordialement

**Comment by nothing-fr** [comment]
Quelle est l'url du chat ? 
Je suis de l'INSA de Rennes.

**Comment by ptitloup** [comment]
et voici : https://rocket.esup-portail.org/group/esup_-_pod

**Comment by ptitloup** [comment]
Cette possibilité a été ajoutée à la V2.8 de Pod #440
