### ISSUE TITLE
Deprecation of the previous pod repository

### ISSUE THREAD

**Issue by lutangar** [EsupPortail/Esup-Pod#524]
There should be a deprecation notice at the top of the previous Pod repository :
https://github.com/EsupPortail/pod

__Problem__
At the moment when reaching for Pod Source code, we first stumble upon this archived repository and there is no mention of the new repository nor a deprecation notice. 
This give the false impression that the Pod project has been abandoned, period.

I didn't find a reason on the "why" that would be a plus to mention it in the deprecation notice. 
I might have overwatch and the reason might exists somewhere in this case just link to the relevant resource.

Deprecation notice might look something like the following:

>*Because [insert reason here] this repository is  now __deprecated__.*
> *Current __Pod__ version is maintained at https://github.com/EsupPortail/Esup-Pod*

> Other  examples of deprecation notices randomly found on Github:
> https://github.com/apache/cordova-blackberry
> https://github.com/betagouv/ecolab-transport

Previous repository may also be renamed to `EsupPortail/Pod-deprecated` (or smthing similar) and new repository could simply take over previous repository name :  `EsupPortail/Pod`.

**Comment by ptitloup** [comment]
Hello Johan, Thank you for this issue ! I will improve it as soon as possible.

**Comment by ptitloup** [comment]
Hello,

I just added some modification : https://github.com/EsupPortail/pod

If you have any more information to add, just tell me

Have a good day !
