### ISSUE TITLE
Vidéos privées et indexation par le moteurs

### ISSUE THREAD

**Issue by kerjoa** [EsupPortail/Esup-Pod#543]
Bonjour,
Des vidéos privées (dont les liens ont été diffusés sans doute) peuvent se retrouver indexées par les robots.
Ceci ne semble pas souhaitable pour les vidéos privées.
Ajouter les balises meta qui vont bien dans une balise meta des pages concernées permettraient d'éviter ces indexations.
`<meta name="robots" content="noindex" />`
Merci.
Johan

**Comment by ptitloup** [comment]
Bonjour, 
Un contributeur au projet, @Badatos , va proposer un ensemble d'amélioration dont la correction des indexations des vidéos. On va rajouter des meta comme vous le proposez. 
N'hésitez pas à nous proposer toutes informations qui pourrait nous aider.
Merci
Nicolas
