### ISSUE TITLE
Faille XSS : Critique sur le paramètre "selected_facets"

### ISSUE THREAD

**Issue by BHoury** [EsupPortail/Esup-Pod#548]
Bonjour,

Sur la version 2.8.2 de Pod, notre RSSI nous a fait remonter une faille XSS critique sur le paramètres "selected_facets"
/search/?q=209171&start_date=%C2%9E%C3%A9e&end_date=%C2%9E%C3%A9e&selected_facets=type.slug%3aotherpapjj%3cscript%3ealert(crt)%3c%2fscript%3eq22ds

Cdt
Benjamin Houry

**Comment by Badatos** [comment]
J'ai testé sur cette adresse (pod en version 2.8) :
https://mediatheque.univ-paris1.fr/search/?q=209171&start_date=%C2%9E%C3%A9e&end_date=%C2%9E%C3%A9e&selected_facets=type.slug%3aotherpapjj%3cscript%3ealert(crt)%3c%2fscript%3eq22ds

Mais je ne vois pas de souci particulier ?

**Comment by Badatos** [comment]
Ok, le lien donné en exemple générait une erreur dans la console. Avec celui-ci c'est plus visuel :

https://mediatheque.univ-paris1.fr/search/?q=209171&start_date=%C2%9Eée&end_date=%C2%9Eée&selected_facets=type.slug%3aFAILLE<script>alert(document.domain)<%2fscript>_XSS
