### ISSUE TITLE
Bouton de ralentissement des vidéos

### ISSUE THREAD

**Issue by kerjoa** [EsupPortail/Esup-Pod#595]
Bonjour,
Un retour d'un enseignant de musique à propos d'une fonctionnalité utile pour sa matière (la fonctionnalité est déjà présente dans le player de Pod mais les possibilités ne sont pas ici pertinentes) :

> Nous mettons de plus en plus de supports de travail pour que les élèves puissent s’entrainer et apprendre les projets musicaux en autonomie. 
> Pour certains supports, il est nécessaire de pouvoir ralentir les vidéos afin de faciliter l’apprentissage. 
> Seulement, le seul 50% disponible actuellement est souvent beaucoup trop lent. 
> La plage pertinente se situe entre 75% et 95%. 

À voir si c'est possible d'avoir une option à "0.75x" ou "0.8x" ou un réglage pour l'obtenir ?
Merci

**Comment by ptitloup** [comment]
Bonjour,
Vous pouvez changer ces valeurs via la variable de configuration suivante : VIDEO_PLAYBACKRATES = '[0.5, 1, 1.5, 2]'
Vous pouvez essayer de mettre '[0.5, 0.6, 0.7, 0.8, 0.9, 1, 1.5, 2]'
Bonne journée
