### ISSUE TITLE
Accès aux fichiers mp4 ou mp3

### ISSUE THREAD

**Issue by kerjoa** [EsupPortail/Esup-Pod#597]
Bonjour,
Certains outils nécessitent d'utiliser les fichiers médias (mp4 ou mp3) en accès direct. Par exemple le module H5P de moodle.
Actuellement, si on active le téléchargement des fichiers, au clic sur les liens, la requête se fait en POST et on n'a pas les URLs des fichiers. Si on cherche bien dans le code html des pages, on sait reconstituer ces URLs mais c'est une solution pour les utilisateurs avertis. L'idéal serait de les proposer dans l'onglet de partage.
Merci.

**Comment by ptitloup** [comment]
Bonjour,
Les propriétaires des vidéos vont trouver des liens direct pour accèder aux versions mp4 des fichiers déposés directement sur l'interface de visualisation de leur vidéo. En quelle version etes-vous ? Je pense qu'il vous faire une mise à jour de la plateforme.
Nicolas

**Comment by kerjoa** [comment]
Merci pour le retour.
Nous sommes en 2.7.2 et je vais demander à nos admins de faire la mise à jour prochainement.
Après ici les non propriétaires de la vidéo n'auront pas ces liens. Il y a peut-être une raison pour laquelle la diffusion de ces liens doit être limitée aux propriétaires...?

Johan

**Comment by ptitloup** [comment]
Ces liens sont des accès direct aux vidéos et de ce fait, peuvent être sensibles.
il faut donc les utiliser avec parcimonie. 
Nicolas
