### ISSUE TITLE
Probleme à l'installation 2.9.2

### ISSUE THREAD

**Issue by CartierPierre** [EsupPortail/Esup-Pod#608]
https://github.com/EsupPortail/Esup-Pod/blob/a5790bd7041f3f46a18bd57be3c6616624d20d1c/pod/video/models.py#L80
J'ai un problème avec cette ligne qui me renvoie :
```
Traceback (most recent call last):
  File "manage.py", line 39, in <module>
    execute_from_command_line(sys.argv)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/django_projects/podv2/pod/video/models.py", line 82, in <module>
    LANG_CHOICES_DICT = {key: value for key, value in LANG_CHOICES[0][1] + LANG_CHOICES[1][1]}
  File "/home/pod/.virtualenvs/django_pod/lib/python3.7/site-packages/django/utils/functional.py", line 115, in __wrapper__
    return getattr(res, method_name)(*args, **kw)
TypeError: can only concatenate str (not "__proxy__") to str
```

Instinctivement j'aurais plutot mis : `LANG_CHOICES_DICT = {key: value for key, value in LANG_CHOICES}`

**Comment by ptitloup** [comment]
Pour ma part, je penche plutot pour un problème de settings

**Comment by CartierPierre** [comment]
Ca continue avec la langue "nl" pas prise en charge
django.core.exceptions.ImproperlyConfigured: MODELTRANSLATION_FALLBACK_LANGUAGES: "nl" not in LANGUAGES setting

**Comment by ptitloup** [comment]
ok alors pour la langue nl, il faut juste mettre ceci dans ton settings-local : 
LANGUAGE_CODE = "fr"
LANGUAGES = (
    ('fr', 'Français'),
    ('en', 'English')
)
MODELTRANSLATION_FALLBACK_LANGUAGES = ('fr', 'en')

**Comment by ptitloup** [comment]
essaye de voir si ca résoud les conflits

**Comment by CartierPierre** [comment]
J'ai remis le nl dans mon settings_local.py, ca ne résout que le bug 'nl', pas les précédents (que j'ia temporairement fixé avec la premiere solution que je propose).
Concernant MODELTRANSLATION_FALLBACK_LANGUAGES, il n'est trouvable que dans le settings.py, pas de le custom, j'imagine qu'il faut donc le surcharger ?

**Comment by ptitloup** [comment]
je comprends pas l'erreur que tu rencontres avec le dict de lang : 
(django_pod) pod@pod:/usr/local/django_projects/podv2$ python manage.py shell
Python 3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.conf import settings
>>> from pod.main.lang_settings import ALL_LANG_CHOICES, PREF_LANG_CHOICES
>>> LANG_CHOICES = getattr(
...     settings, 'LANG_CHOICES', (
...         (' ', PREF_LANG_CHOICES),
...         ('----------', ALL_LANG_CHOICES)
...     ))
>>> LANG_CHOICES_DICT = {
...     key: value for key,
...     value in LANG_CHOICES[0][1] + LANG_CHOICES[1][1]
... }
>>> LANG_CHOICES_DICT
{'de': 'German', 'en': 'English', 'ar': 'Arabic', 'zh': 'Chinese', 'es': 'Spanish', 'fr': 'French', 'it': 'Italian', 'ja': 'Japanese', 'ru': 'Russian', 'ab': 'Abkhazian', 'aa': 'Afar', 'af': 'Afrikaans', 'sq': 'Albanian', 'am': 'Amharic', 'an': 'Aragonese', 'hy': 'Armenian', 'as': 'Assamese', 'ay': 'Aymara', 'az': 'Azerbaijani', 'ba': 'Bashkir', 'eu': 'Basque', 'bn': 'Bengali (Bangla)', 'dz': 'Bhutani', 'bh': 'Bihari', 'bi': 'Bislama', 'br': 'Breton', 'bg': 'Bulgarian', 'my': 'Burmese', 'be': 'Byelorussian (Belarusian)', 'km': 'Cambodian', 'ca': 'Catalan', 'co': 'Corsican', 'hr': 'Croatian', 'cs': 'Czech', 'da': 'Danish', 'nl': 'Dutch', 'eo': 'Esperanto', 'et': 'Estonian', 'fo': 'Faeroese', 'fa': 'Farsi', 'fj': 'Fiji', 'fi': 'Finnish', 'fy': 'Frisian', 'gl': 'Galician', 'gd': 'Gaelic (Scottish)', 'gv': 'Gaelic (Manx)', 'ka': 'Georgian', 'el': 'Greek', 'kl': 'Greenlandic', 'gn': 'Guarani', 'gu': 'Gujarati', 'ht': 'Haitian Creole', 'ha': 'Hausa', 'he': 'Hebrew', 'hi': 'Hindi', 'hu': 'Hungarian', 'is': 'Icelandic', 'io': 'Ido', 'id': 'Indonesian', 'ia': 'Interlingua', 'ie': 'Interlingue', 'iu': 'Inuktitut', 'ik': 'Inupiak', 'ga': 'Irish', 'jv': 'Javanese', 'kn': 'Kannada', 'ks': 'Kashmiri', 'kk': 'Kazakh', 'rw': 'Kinyarwanda (Ruanda)', 'ky': 'Kirghiz', 'rn': 'Kirundi (Rundi)', 'ko': 'Korean', 'ku': 'Kurdish', 'lo': 'Laothian', 'la': 'Latin', 'lv': 'Latvian (Lettish)', 'li': 'Limburgish ( Limburger)', 'ln': 'Lingala', 'lt': 'Lithuanian', 'mk': 'Macedonian', 'mg': 'Malagasy', 'ms': 'Malay', 'ml': 'Malayalam', 'mt': 'Maltese', 'mi': 'Maori', 'mr': 'Marathi', 'mo': 'Moldavian', 'mn': 'Mongolian', 'na': 'Nauru', 'ne': 'Nepali', 'no': 'Norwegian', 'oc': 'Occitan', 'or': 'Oriya', 'om': 'Oromo (Afaan Oromo)', 'ps': 'Pashto (Pushto)', 'pl': 'Polish', 'pt': 'Portuguese', 'pa': 'Punjabi', 'qu': 'Quechua', 'rm': 'Rhaeto-Romance', 'ro': 'Romanian', 'sm': 'Samoan', 'sg': 'Sangro', 'sa': 'Sanskrit', 'sr': 'Serbian', 'sh': 'Serbo-Croatian', 'st': 'Sesotho', 'tn': 'Setswana', 'sn': 'Shona', 'ii': 'Sichuan Yi', 'sd': 'Sindhi', 'si': 'Sinhalese', 'ss': 'Siswati', 'sk': 'Slovak', 'sl': 'Slovenian', 'so': 'Somali', 'su': 'Sundanese', 'sw': 'Swahili (Kiswahili)', 'sv': 'Swedish', 'tl': 'Tagalog', 'tg': 'Tajik', 'ta': 'Tamil', 'tt': 'Tatar', 'te': 'Telugu', 'th': 'Thai', 'bo': 'Tibetan', 'ti': 'Tigrinya', 'to': 'Tonga', 'ts': 'Tsonga', 'tr': 'Turkish', 'tk': 'Turkmen', 'tw': 'Twi', 'ug': 'Uighur', 'uk': 'Ukrainian', 'ur': 'Urdu', 'uz': 'Uzbek', 'vi': 'Vietnamese', 'vo': 'Volapük', 'wa': 'Wallon', 'cy': 'Welsh', 'wo': 'Wolof', 'xh': 'Xhosa', 'yi': 'Yiddish', 'yo': 'Yoruba', 'zu': 'Zulu'}
>>>

**Comment by ptitloup** [comment]
tu peux essayer de ton côté mais ca devrait fonctionner sans modifications de tes settings

**Comment by ptitloup** [comment]
Pour le nl, c'est à toi de voir si tu veux le garder ou pas

**Comment by CartierPierre** [comment]
Je continue, 
https://github.com/EsupPortail/Esup-Pod/blob/a5790bd7041f3f46a18bd57be3c6616624d20d1c/pod/custom/settings_local.py.example#L759
Qui génère l'erreur 
File "/usr/local/django_projects/podv2/pod/video/forms.py", line 328, in <module>
    VIDEO_FORM_FIELDS_HELP_TEXT.update(transcript_help_text)
AttributeError: 'str' object has no attribute 'update'

**Comment by ptitloup** [comment]
mais arrete, si tu mets toutes tes erreurs ici, on ne va plus t'aider. Et ne continue pas si tu ne résouds pas le précédent bug.
Tu ne respectes pas la forme des variables leur typage.

**Comment by ptitloup** [comment]
> LANG_CHOICES j'ai (('fr', Français'),('de' 'Allemand'),('en', 'Anglais'),
Il faut respecter le typage des variables dans leur surcharge de ton fichier de configuration. Pour LANG_CHOICES, on attends la concatenation de deux listes. je pense que c'est pour cela que tu rencontres des erreurs.

**Comment by CartierPierre** [comment]
En fait j'ai l'impression que toutes les erreurs viennent de certains paramètres par défaut dans pod/custom/settings_local.py
Si je compare LANG_CHOICE :
https://github.com/EsupPortail/Esup-Pod/blob/a5790bd7041f3f46a18bd57be3c6616624d20d1c/pod/custom/settings_local.py.example#L681
et
https://github.com/EsupPortail/Esup-Pod/blob/a5790bd7041f3f46a18bd57be3c6616624d20d1c/pod/video/models.py#L65

**Comment by ptitloup** [comment]
pour ton pod/custom/settings_local.py, il ne faut pas reprendre le example et le modifier mais partir d'un fichier vide que tu modifies selon ton besoin.

**Comment by CartierPierre** [comment]
Ah, je reprenais betement le .example justement, pensant que toutes les valeurs par défault étaient bonnes, bon bah je repart d'un fichier vierge et je vous tiens au courant, ca devrait résoudre les problèmes.

**Comment by ptitloup** [comment]
> Fichier de configuration settings_local.py
Vous devez créer un fichier de configuration local dans le dossier pod/custom.
Vous mettez dans ce fichier uniquement les variables dont vous voulez changer la valeur par défaut. Vous trouverez ci-dessous un exemple de fichier avec les principales variables à modifier : connexion à la base de donné, un fichier css custom, le thème green de pod, retirer le langage nl, etc ... Vous pouvez adapter ce fichier et le coller dans le votre.
