### ISSUE TITLE
Prendre en compte les sous-titles des fichiers téléversés

### ISSUE THREAD

**Issue by baby-gnu** [EsupPortail/Esup-Pod#638]
Bonjour.

Lorsque j’envois un fichier contenant déjà les sous-titres, ceux-ci ne sont pas pris en compte lors de la conversion.

Les flux de sous-titre devraient être copiés tels-quels.

Merci.

**Comment by ptitloup** [comment]
Bonjour,
les fichiers de sous-titres sont inclus dans le container ?
Sinon, à quel établissement appartenez-vous ? 
Serait-ce possible de nous aider à contribuer à ce projet en proposant cette fonctionnalité ?
Merci beaucoup

**Comment by ptitloup** [comment]
Merci, je transfert également votre demande à la direction du numérique pour l'éducation qui gère votre instance.
N'hésitez pas à revenir vers moi pour tout complément d'information, je laisse votre demande ouverte.
Bien cordialement

**Comment by ptitloup** [comment]
Bonjour, 
Votre demande a été prise en compte et est maintenant intégrée dans la dernière version de la plateforme
Bien cordialement
