### ISSUE TITLE
Openid Redirection après authentification

### ISSUE THREAD

**Issue by BHoury** [EsupPortail/Esup-Pod#688]
**problème**: nous avons remarqué que l'authentification avec l'openid pour une vidéo https://url/_mon_pod/video/0010-test1 accessible après authentification ne prend pas en compte l'url de la vidéo. Par exemple pour la vidéo test1, le lien généré pour l'authentification locale : https://url/_mon_pod/accounts/login/?next=/video/0010-test1 et pour l'authentification openid l'url générée est https://url/_mon_pod/accounts/oidc/authenticate/ alors qu'elle devrait être https://url/_mon_pod/accounts/oidc/authenticate/?next=/video/0010-test1 pour que l'on soit renvoyé après authentification à la vidéo.

**solution** : modifier le fichier Esup-Pod/pod/authentication/templates/authentication/login.html
et ajouter ?{% if [request.GET.is](http://request.get.is/)_iframe %}is_iframe=true&amp;{%endif%}next={{ referrer|urlencode }} après {%url 'oidc_authentication_init' %}

->href="{%url 'oidc_authentication_init' %}?{% if [request.GET.is](http://request.get.is/)_iframe %}is_iframe=true&amp;{%endif%}next={{ referrer|urlencode }}"

**Comment by ptitloup** [comment]
Normalement, le is_iframe est déjà dans l'url, il n'est pas nécessaire de le préciser. On le rajoute juste dans le local login pour afficher correctement le formulaire dans Pod, on ne le précise pas pour les autres, l'authentification etant déléguée.

**Comment by ptitloup** [comment]
https://github.com/EsupPortail/Esup-Pod/pull/678/commits/7a484dbe50264b0af88d8de69676be570607ccc0
