### ISSUE TITLE
Bug enregistreur option sans audio

### ISSUE THREAD

**Issue by BHoury** [EsupPortail/Esup-Pod#701]
Bonjour,

Sur la V3.0.3 quand on fait un enregistrement avec l'enregistreur opencast avec l'option "sans audio" alors Pod n'encode pas la vidéo en mp4 (360 et 720) (mp4_command -> false). Si ensuite on active l'option "téléchargement" pour cette vidéo cela génère une erreur sur Pod (erreur 500 pour les utilisateurs).

Benjamin

**Comment by ptitloup** [comment]
tu peux renvoyer les commandes depuis le fichier json.
Merci

**Comment by BHoury** [comment]
Bonjour,
Ci-joint le fichier de log de l'encodage

[info_video.txt](https://github.com/EsupPortail/Esup-Pod/files/10004486/info_video.txt)

**Comment by ptitloup** [comment]
#705
