### ISSUE TITLE
Tags obligatoires

### ISSUE THREAD

**Issue by FBrosset** [EsupPortail/Esup-Pod#714]
Bonjour,

serait-il possible d'avoir une option générale pour rendre les tags obligatoires .

Cordialement.

**Comment by ptitloup** [comment]
Bonjour, voici le paramètre qu'il faut utiliser pour ceci : 
"""
# Gerer des champs obligatoires dans le formulaire d'edition et
# d'ajout d'une video:
# Exemple valeur: ["discipline", "tags"]
# NB: les champs cachés et suivant ne sont pas pris en compte:
# (video, title, type, owner, date_added, cursus, main_lang)
#
"""
VIDEO_REQUIRED_FIELDS = []
