### ISSUE TITLE
Reflected XSS : /videos/ dans le param "owner"

### ISSUE THREAD

**Issue by jhond0e** [EsupPortail/Esup-Pod#728]
Bonjour,

La version 3.0.5 (et antérieures) de Esup-Pod comporte une vulnérabilité de type "Reflected XSS" au chemin "/videos/" dans le paramètre "owner".
Un payload fonctionnel est "</script><script>alert(document.domain)</script>"
Pour vérifier la vulnérabilité, rendez vous à l'url "/videos/?owner=</script><script>alert(document.domain)</script>" sur votre instance POD.
Pour fixer la vulnérabilité, filtrez les données entrées dans le paramètre owner.

**Comment by Badatos** [comment]
Merci pour ce retour ! normalement le patch ci-dessus devrait régler le souci.
