### ISSUE TITLE
Modification des heures en cours de live

### ISSUE THREAD

**Issue by mattbild** [EsupPortail/Esup-Pod#774]
Lorsqu'un utilisateur (non admin) veut modifier un évènement en cours, la soumission du formulaire renvoie une erreur.

![erreur](https://user-images.githubusercontent.com/34771705/224674118-68749027-7fec-4a7a-8762-749a0c011113.png)

Ce bug est corrigé dans la PR #726, "ajout Qrcode sur diffuseur pour création évènement immédiat", en date du 20/01.

Il s'agit de la methode **update_event** : 
[https://github.com/EsupPortail/Esup-Pod/pull/726/files#diff-d8ac304ca55a54dd8ee6d36faee84e3cf5680fb5591acac59d8c1d86246f1367R503-R509](https://github.com/EsupPortail/Esup-Pod/pull/726/files#diff-d8ac304ca55a54dd8ee6d36faee84e3cf5680fb5591acac59d8c1d86246f1367R503-R507)

Est-il possible de créer un hotfix depuis 3.0.5 (seule version a être impactée) ?

**Comment by ptitloup** [comment]
Hello, je regarde ca et reviens vers vous

**Comment by ptitloup** [comment]
Après test, il n'est pas possible de sortir ce hotfix sans conflit avec la branche develop. Le problème est que le conflit est sur le fichier en entier (donc pas résolvable immédiatement)... cette issue sera donc résolue avec la 3.1
