### ISSUE TITLE
Un paramètre supplémentaire pour l'affichage des dernières vidéo sur la homepage

### ISSUE THREAD

**Issue by cbissler** [EsupPortail/Esup-Pod#796]
Bonjour,

Nous avons constaté que les dernières vidéos qui s'affichent sur la page d'accueil de POD excluent les vidéos qui sont dans une chaine non visible. Une vidéo pouvant être dans plusieurs chaines c'est un peu compliqué. Dans notre usage, nous avons beaucoup de chaines que nous comptons laisser privées ça exclue les vidéos de la page d'accueil.
Est-ce que ce serait possible d'ajouter un paramètre de configuration (comme pour les vidéos à accès restreint) qui permettra à l'établissement de choisir s'il souhaite ou non que les vidéos associées à une chaine privée apparaisse sur la page d'accueil ?

Merci d'avance pour l'étude de la question

**Comment by ptitloup** [comment]
Il faut voir le bout de code suivant : **https://github.com/EsupPortail/Esup-Pod/blob/master/pod/video/templatetags/video_tags.py#L79**

**Comment by ptitloup** [comment]
Il faut en profiter pour appeler la focntion get_availabel_video dans la  fcontion get last video : https://github.com/EsupPortail/Esup-Pod/blob/master/pod/video/templatetags/video_tags.py#L81
