### ISSUE TITLE
Erreur 500 lors de l'ajout d'une vidéo depuis l'interface d'admin

### ISSUE THREAD

**Issue by ericdacosta** [EsupPortail/Esup-Pod#819]
Bonjour,
Nous avons constaté un bug depuis la version 3.1.1, lors de l'ajout d'une vidéo depuis l'interface d'admin, nous avons une erreur 500. Ci-dessous les logs obtenus : 

>   File "/home/pod/.virtualenvs/django_pod3/lib/python3.9/site-packages/django/forms/forms.py", line 155, in __getitem__
>     raise KeyError(
> KeyError: "Key 'video' not found in 'VideoForm'. Choices are: additional_owners, allow_downloading, channel, cursus, date_added, date_evt, description, description_en, description_fr, description_nl, discipline, is_360, is_draft, is_restricted, licence, main_lang, password, restrict_access_to_groups, sites, tags, theme, thumbnail, title, title_en, title_fr, title_nl, transcript, type."
> Internal Server Error: /admin/video/video/add/
> Traceback (most recent call last):
>   File "/home/pod/.virtualenvs/django_pod3/lib/python3.9/site-packages/django/forms/forms.py", line 153, in __getitem__
>     field = self.fields[name]
> KeyError: 'video'

**Comment by ptitloup** [comment]
Voilà la PR : https://github.com/EsupPortail/Esup-Pod/pull/834
