### ISSUE TITLE
[FEATURE] Publish video as unlisted

### ISSUE THREAD

**Issue by CartierPierre** [EsupPortail/Esup-Pod#902]
Hi,
I have some users who wants to publish their video without password, but not visible or findable with search bar, like the unlisted on YouTube. veiwers can only see it from a link.

**Comment by ptitloup** [comment]
Hello Pierre, users can let video in draft mode and use share link (with hash inside url) to share video

**Comment by CartierPierre** [comment]
Hum, yes but it points to the video ressource directly, without iframe, quality selection, subtitles and all other features around the video itself.

**Comment by ptitloup** [comment]
no, you can use the share link with the video in draft mode

**Comment by CartierPierre** [comment]
Oh super !
