### ISSUE TITLE
Bouton transcription qui n'apparait pas toujours

### ISSUE THREAD

**Issue by CartierPierre** [EsupPortail/Esup-Pod#906]
Bonjour, 
Avec les vidéos issues de pod2 (je suis en v3.2), en statut "0: Done" , il n'est pas possible d'avoir le bouton pour relancer une transcription.
Ce bouton disparait aussi dès que nous avons fait une transcription (l'utilisateur peut se tromper de langue et devoir relancer une transcription), car le statut passe de "0: end of encoding" à "0: done", c'est la ligne ci dessous qui conditionne l'affichage du bouton.
https://github.com/EsupPortail/Esup-Pod/blob/0a65f065a4b63492f5845c0eb59ed17768b6cc3e/pod/video/templates/videos/video_edit.html#L118

J'ai également remarqué que quand l'utilisateur lance une transcription sans sélectionner de modèle, le code d'erreur "-1: no stt model [...]" vient bloquer le bouton et empêche toute nouvelle transcription.

De mon coté j'ai patché ça à la main avec cette ligne 
``` python
{% if form.instance.slug != '' and form.instance.get_encoding_step|slice:":1" == '0' or 'no stt model' in form.instance.get_encoding_step %}
```

Cependant ce n'est pas encore très user friendly, car il faut sélectionner la langue de transcription, valider les changements dans le bas de formulaire, puis cliquer sur le bouton "relancer la transcription".

**Comment by ptitloup** [comment]
Bonjour Pierre,
C'est fixé en V3.3.1. Il est possible de choisir la langue de la transcription et de la relancer si beson.
Nicolas
