### ISSUE TITLE
Conditions pour masquer des filtres

### ISSUE THREAD

**Issue by DeprezLaurent** [EsupPortail/Esup-Pod#915]
Bonjour, est-ce qu'il serait possible dans filter_aside.html d'ajouter des conditions à l'affichage des filtres ?
Par exemple : 

`{% if HIDE_DISCIPLINES == False %}
<fieldset class="border-right border-bottom mt-2">
  <legend class="h5"><i class="bi bi-book"></i> {% trans "Disciplines"%} </legend>
  <div id="filterDiscipline">
    <div class="form-group collapse" id="collapseFilterDiscipline">
      {% for discipline in DISCIPLINES %}
        <div class="form-check">
          <input class="form-check-input" type="checkbox" name="discipline"
            value="{{discipline.slug}}" id="id{{discipline.slug.split|join:'-'}}_disc" {% if discipline.slug in disciplines %}checked{% endif %}>
          <label class="form-check-label" for="id{{discipline.slug.split|join:'-'}}_disc">
            {% if discipline.icon %}<img src="{{discipline.icon.file.url}}" alt="{{discipline.title}}" style="max-height:32px; max-width:32px;" loading="lazy">{% endif %}&nbsp;{{discipline}}
          </label>
        </div>
      {%endfor%}
    </div>
    {% if DISCIPLINES.count > 5 %}
      <span class="badge badge-light float-end"><a class="collapsed" data-bs-toggle="collapse" href="#collapseFilterDiscipline" aria-expanded="false" aria-controls="collapseFilterDiscipline"></a></span>
    {% endif %}
  </div>
</fieldset>
    {% endif %}
` 
Merci (Et bonne rentrée à tous!)
  Laurent

**Comment by ptitloup** [comment]
Bonjour Laurent,
Je regarde ca.
Bonne rentrée à vous aussi !
