### ISSUE TITLE
[Bug] Page d’affichage vidéos par owner n’affiche pas uniquement les vidéos de l’utilisateur

### ISSUE THREAD

**Issue by sabinanina** [EsupPortail/Esup-Pod#926]
Dans la page d’affichage des vidéos par utilisateur [notreinstancepod.fr/videos/?owner=id_utilisateur(4Jzl9rebLD-j17OtnKjHloazUco) ], les 12 premières vidéos appartiennent effectivement à l’utilisateur en question, mais à partir de la 13ème vidéo, on affiche les vidéos de la page « notreinstancepod.fr/videos/ ». 

Il semblerait qu'au moment de scroller vers le bas pour voir les vidéos suivantes, le filtre « owner » soit perdu.

On observe ce dysfonctionnement en étant connecter et déconnecté.

Sabina Caviedes

**Comment by pampletousse** [comment]
Bonjour Sabina,

Etes-vous sûre que ce n'est pas parce que les vidéos suivantes (à partir de la 13ème) ne sont pas à l'utilisateur en question mais en tant que "propriétaire additionnel" ? J'investigue mais je n'arrive pas à reproduire le bug sur notre instance pour le moment.

Pouvez-vous également me donner la version de Pod sur laquelle vous êtes ? Merci.

Sylvain Loppin

**Comment by sabinanina** [comment]
Bonjour Sylvain,

Je viens de vérifier avec mes vidéos. J’ai plus de 12 vidéos dont je suis la propriétaire principale ou l’unique propriétaire. 
De plus parmi les 12 premières vidéos Pod propose au moins une vidéo où je suis propriétaire additionnelle.

La version de notre instance est 3.1.1 et j’ai testé également en pre-prod la 3.3.1

Un exemple ici : https://podeduc.apps.education.fr/videos/?owner=sabina
La vidéo n°13 de cette page et la même vidéo n°13 de la page d’accueil et ainsi de suite…

Merci à vous
Sabina

**Comment by sabinanina** [comment]
Bonjour Sylvain,
Je suis allée voir sur le Pod de l'université de Lille et j'ai trouvé le même problème.
Sur la page https://pod.univ-lille.fr/videos/?owner=jean-luc.tessier on annonce 19 vidéos. 
Pod affiche les 12 premières vidéos appartenant à cet utilisateur, mais dès qu'on scrolle pour voir les autres vidéos on affiche tous les vidéos de Pod.
Vous arrivez à le voir ?
Encore merci :)
Sabina

**Comment by pampletousse** [comment]
Bonjour Sabine !

J'ai résolu le bug est il sera disponible dans une prochaine version de Pod.

Par contre une petite précision sur la fonctionnalité :
Si l'utilisateur n'est pas authentifié ET/OU que la fonctionnalité HIDE_FILTER_USER est activée (cf. configuration de l'instance) il n'est pas permis à la personne de rechercher les vidéos par user et ce dernier n'apparaîtra pas dans les filtres dans l'encart de droite (en accord avec les règles RGPD = protection des données européennes).

Donc si vous avez par exemple gardé l'url que vous m'avez envoyé en favoris, il est possible qu'elle ne fonctionne plus selon la configuration de votre application. Désormais, si cette requête n'est pas autorisée, vous aurez la liste totale des vidéos mais avec une url correspondante, nettoyée : https://pod.univ-lille.fr/videos/

Le compteur de vidéos devrait être lui aussi en accord avec la liste affichée !

Sylvain Loppin.

**Comment by sabinanina** [comment]
C'est super Sylvain ! 
Merci beaucoup pour l'info, la résolution du bug et toutes ces précisions !
A très bientôt
