### ISSUE TITLE
Ré organisation des vidéos favorites

### ISSUE THREAD

**Issue by DeprezLaurent** [EsupPortail/Esup-Pod#939]
Lorsqu'on sauvegarde une ré organisation des vidéos favorites on obtient la page d'erreur ci-jointe.
Testé sur notre pre prod en 3.3.1

![Screenshot 2023-09-07 at 09-35-58 IntegrityError at _favorite_save-reorganisation_](https://github.com/EsupPortail/Esup-Pod/assets/87009850/919d157e-808c-4be5-b1ab-ce3c58f102f2)

**Comment by ptitloup** [comment]
Bonjour, merci pour cette remontée d'information, nous allons regarder rapidement.

**Comment by ptitloup** [comment]
Bonjour, je viens de regarder et j'ai constaté le pb.
Voici un patch qui permet d'y pallier : 
```
diff --git a/pod/favorite/views.py b/pod/favorite/views.py
index d9c08906..8c926ea8 100644
--- a/pod/favorite/views.py
+++ b/pod/favorite/views.py
@@ -113,8 +113,9 @@ def favorites_save_reorganisation(request):
                 )
                 video_1_rank = fav_video_1[0].rank
                 video_2_rank = fav_video_2[0].rank
-                fav_video_1.update(rank=video_2_rank)
+                fav_video_1.update(rank=-1)
                 fav_video_2.update(rank=video_1_rank)
+                fav_video_1.update(rank=video_2_rank)
 
         return redirect(request.META["HTTP_REFERER"])
     else:
```
Peux-tu me dire si cela convient ? j'ai testé dans la future versoin 3.4.0 et ce pb est résolu

**Comment by DeprezLaurent** [comment]
Merci, on teste de notre côté et on te dit
