### ISSUE TITLE
Problème d'affichage réservation de réunion BBB à occurrence multiple

### ISSUE THREAD

**Issue by frouze** [EsupPortail/Esup-Pod#941]
J'ai testé sur Firefox et Chrome sous Windows la création d'une réunion BBB via le POD  v3.3.1 de ULille et je rencontre le soucis d'affichage suivant :
J'ai voulu créer une réunion avec une récurrence, lors du choix de la date de fin l'affichage du dialogue de choix de date s'est affiché tout en haut du navigateur et seul le bas du dialogue était visible, pas le calendrier.  Je précise que ce n'est pas à chaque coup mais que je l'ai vu à plusieurs reprises sur 2 PCs différents et pas toujours su la même taille de fenêtre de navigateur. C'est assez étrange.
![Sans titre](https://github.com/EsupPortail/Esup-Pod/assets/9482543/3c01acb4-5fb7-44d5-a46c-8e39b17af893)

**Comment by ptitloup** [comment]
Bonjour Franck,
Merci pour ton retour.
Je regarde de mon côté et te tiens informé
Nicolas

**Comment by ptitloup** [comment]
#946

**Comment by ptitloup** [comment]
le probleme d'affichage vient du calcul de la position du calendrier quand il est dans une modal, pour fixer le pb, je change sa position en "fixed"
