### ISSUE TITLE
Erreur 500 lors de la validation d'une réunion avec récurrence

### ISSUE THREAD

**Issue by frouze** [EsupPortail/Esup-Pod#942]
J'ai tenté de faire une réunion avec récurrence sous Chrome, et FF via le POD v3.3.1 de ULille et j'ai eu un souci lors de la validation de celui-ci.
J'ai tenté soit en choisissant une date de fin soit en spécifiant le nombre d'occurences et dans les deux cas j'ai droit à une erreur 500 lors de la validation finale de ma réservation.

cas 1 (date de fin) : 
![image](https://github.com/EsupPortail/Esup-Pod/assets/9482543/61d45c43-a016-462b-829a-b562977d936a)
Résultat à la validation de ma réunion
![image](https://github.com/EsupPortail/Esup-Pod/assets/9482543/c23bbe7c-c939-46a0-9808-a3f3fe729625)

cas 2 (nombre d'occurences) : 
![image](https://github.com/EsupPortail/Esup-Pod/assets/9482543/c676ec8c-a46a-4b96-b61e-1d88588e7de7)
Résultat à la validation de ma réunion
![image](https://github.com/EsupPortail/Esup-Pod/assets/9482543/f301eacf-74ed-4bf5-ba02-7e56295e554b)

**Comment by ptitloup** [comment]
Bonjour Franck et merci pour cette remontée d'information.
L'erreur est due au fait de selectionnée une récurrence sur un jour qui n'est pas celui de la date de debut de la réunion.
Par exemple, nous sommes mardi et je créé une reunion pour tous les lundi.
Maintenant, comment vois-tu cette correction, faut-il selectionné le jour correspondant à celui de la date de début ou faut-il modifier la date de debut en fonction de la réccurence?
Quel est ton avis ?
Merci
Nicolas

**Comment by frouze** [comment]
Salut Nicolas,
Pour moi l'idée est d'ajouter les occurrences correspondants aux jours sélectionnés et qui précèdent la date de fin choisie.

Dans le cas simple : 
date début = lundi, jours sélectionné = lundi et récurrence jusqu'à un mardi plus tard dans le calendrier. => on prend tous les lundis jusqu'à la veille du "mardi de fin"

dans un cas plus complexe : 
date début = lundi, jours sélectionnés = lundi et jeudi avec récurrence jusqu'à un mardi => on prend tous les lundi et jeudi des semaines antérieures au mardi final plus le dernier lundi

dans un cas plus tordu
date de début un lundi, date sélectionnée un mercredi et un jeudi avec récurrence jusqu'à un mardi => prendre le lundi de départ dont on suppose qu'il est le lancement de la récurrence puis les mercredi et jeudi suivants et qui précèdent le mardi final. Ou autre alternative ne pas prendre le premier lundi considéré comme un bug mais à ce moment alerter sur le choix étrange.

Je pense que ça semble assez cohérent. mais à voir si il y a mieux.
A+
Franck
