### ISSUE TITLE
Erreur python caractères spéciaux description video

### ISSUE THREAD

**Issue by CartierPierre** [EsupPortail/Esup-Pod#943]
Bonjour, une erreur python apparait lorsqu'on essaie d'ajouter des caractères UTF-8 spéciaux comme 🚀  ou 📁   
```
"Incorrect string value: '\\xF0\\x9F\\x9A\\x80 E...' for column `pod`.`video_video`.`description` at row 1"
```
Je suis en pod 3.2.0.
C'est peut etre un probleme d'encodage coté BDD (mariadb ?)
Bonne journée

**Comment by Badatos** [comment]
Je viens de tester sur Pod 3.3.1 avec MariaDB et je confirme le bug.
Par contre sur Pod 3.3.1 et SQLite ca fonctionne, ce qui confirmerait à priori le problème côté MariaDB.

**Comment by CartierPierre** [comment]
Je vais regarder l'encodage de mes tables, de tête Innodb UTF8

**Comment by Badatos** [comment]
Il faudrait regarder l'encodage exact.
Les icones en question sont peut-être incluses en ut8mb4 mais pas en ut8mb3

https://mariadb.com/kb/en/unicode/

**Comment by CartierPierre** [comment]
Je suis en utf8mb4_general_ci, mariadb version 15.1 Distrib 10.5.19-MariaDB

**Comment by Badatos** [comment]
Dans ce cas, est-il possible que ces icones soient stockées en utf16 ou utf32 ?

**Comment by Badatos** [comment]
aah je vois également sur Internet qu'ils recommandent `utf8mb4_unicode_ci` plutot que `utf8mb4_general_ci`.
Le souci doit venir de là.

https://stackoverflow.com/questions/766809/whats-the-difference-between-utf8-general-ci-and-utf8-unicode-ci

**Comment by CartierPierre** [comment]
Bonjour, j'ai passé la db en collation `utf8mb4_unicode_ci` mais toujours l'erreur.

Bon effectivement, j'ai oublié ce détail, il faut définir au niveau de django le paramètre d'encodage dans les options DB : https://stackoverflow.com/a/20349552

Donc là ca marche nickel ;)
