### ISSUE TITLE
 Vidéos enrichies dans les listes de lecture

### ISSUE THREAD

**Issue by DeprezLaurent** [EsupPortail/Esup-Pod#998]
Lorsqu’on clique sur une vidéo enrichie dans une liste de lecture, on sort de la liste. Cela empêche le démarrage de la liste si la vidéo se trouve en première position

**Comment by SebastienCozeDev** [comment]
Bonjour, après de nombreux tests, je n'ai pas réussi à reproduire le bug. Si j'ai bien compris, lorsqu'une vidéo enrichie se retrouve en première position dans une liste de lecture et que l'on clique dessus, elle se lit comme si elle n'était pas dans la liste ?
